<a href="https://colab.research.google.com/github/lilxmx/DeepLearning-pytorch/blob/main/DL_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1.tensor

In [4]:
import torch

x = torch.empty(5, 3)
print(type(x))
print(x.dtype)
print(x)

<class 'torch.Tensor'>
torch.float32
tensor([[-6.7065e+07,  3.0648e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  3.0648e-41],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22],
        [ 4.5828e+30,  1.2121e+04,  7.1846e+22],
        [ 9.2198e-39,  7.0374e+22, -1.4291e+07]])


### 0、1初始化

In [ ]:
tensor_ones = torch.ones(2,3)
print(tensor_ones.dtype)
print(tensor_ones)
tensor_zeros = torch.zeros(2,3)
print(tensor_zeros.dtype)
print(tensor_zeros)
tensor_zeros_int = torch.zeros(2,3,dtype=torch.long)
print(tensor_zeros_int.dtype)

torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.int64


### 随机初始化
- torch.rand:生成服从区间[0,1)均匀分布的随机张量
- torch.randn:生成服从均值为0、方差为1正太分布的随机张量

In [ ]:
torch_rand = torch.rand(4,2)
print(torch_rand)
torch_randn = torch.randn(3,4)
print(torch_randn)

tensor([[0.0103, 0.0444],
        [0.9518, 0.7599],
        [0.3008, 0.7977],
        [0.1023, 0.0748]])
tensor([[-0.3452,  1.4190, -1.5034,  0.7290],
        [ 0.9279,  0.5008,  0.0441, -0.5407],
        [ 1.6513, -0.3367,  1.6356, -0.5487]])


### 已有数据进行初始化
- 普通python数据结构
- 基于已有的tensor来创建新的tensor，通常是为了复用已有tensor的一些属性，包括shape和dtype

In [ ]:
datalist = [3,2,3,4]
print(torch.tensor(datalist))

tensor([3, 2, 3, 4])


In [ ]:
x = torch.tensor([5.5, 3], dtype=torch.double)
print(x,x.dtype)
x = x.new_ones(5, 3)      # new_* methods take in sizes
print(x,x.dtype)
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x,x.dtype)                                      # result has the same size


`new_ones`函数复用了x的dtype属性，`randn_like`函数复用了x的shape同时通过手动指定数据类型覆盖了原有的dtype属性

### 大小size
torch.Size本质上是一个tuple，通过上面的例子也可以看出，它支持元组的操作。

In [ ]:
x_size = x.size()
print(x_size)
row, col = x_size
print(row, col)

torch.Size([5, 3])
5 3


### torch.arange
用于生成一定范围内等间隔的一维数组。参数有三个，分别是范围的起始值、范围的结束值和步长，使用示例：

In [ ]:
print(torch.arange(1,10,1))

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


## 2.Operations

Operations(操作)涉及的语法和函数很多，大多数都是相通的，下面我们列举一些常用操作及其用法示例。

### 张量间的元素级的四则运算，加减乘除

有多种不同的使用方法，以加法为例：
- 语法1:`x+y`
- 语法2:`torch.add(x,y)`
- 语法3:`torch.add(x,y,out=z3)` 通过参数的形式进行输出tensor的保存
- 语法4：通过in-place操作直接将计算结果覆盖到y上,`y.add_(x)`。在Pytorch中，我们约定凡是会覆盖函数调用主体的in-place操作，都以后缀`_`结束，例如：
`x.copy_(y)`，`x.t_()`，都会改变x的取值。

In [ ]:
x = torch.rand(5,3)
y = torch.ones(5,3)
print('语法1：'),print(x+y)
print('语法2：'),print(torch.add(x,y))
z3 = torch.ones(5,3)
torch.add(x,y,out=z3)
print('语法3：')
print(z3)
print('语法4：')
print(y.add_(x))

语法1：
tensor([[1.4531, 1.8229, 1.8791],
        [1.2508, 1.9210, 1.7967],
        [1.1293, 1.7158, 1.7907],
        [1.6583, 1.1473, 1.9914],
        [1.9093, 1.8684, 1.8893]])
语法2：
tensor([[1.4531, 1.8229, 1.8791],
        [1.2508, 1.9210, 1.7967],
        [1.1293, 1.7158, 1.7907],
        [1.6583, 1.1473, 1.9914],
        [1.9093, 1.8684, 1.8893]])
语法3：
tensor([[1.4531, 1.8229, 1.8791],
        [1.2508, 1.9210, 1.7967],
        [1.1293, 1.7158, 1.7907],
        [1.6583, 1.1473, 1.9914],
        [1.9093, 1.8684, 1.8893]])
语法4：
tensor([[1.4531, 1.8229, 1.8791],
        [1.2508, 1.9210, 1.7967],
        [1.1293, 1.7158, 1.7907],
        [1.6583, 1.1473, 1.9914],
        [1.9093, 1.8684, 1.8893]])


张量之间的减法、点乘和点除的用法是类似的：

In [ ]:
a =torch.randn(2,3)
print(a)
b =torch.randn(2,3)
print(b)

c =torch.sub(a, b)
print(c)
d =torch.mul(a, b)
print(d)
e =torch.div(a, b)
print(e)


tensor([[-0.1725,  0.4341,  0.0860],
        [ 0.5087, -1.1133,  1.2905]])
tensor([[ 0.9284, -2.3935, -0.7159],
        [ 0.9997, -0.5603, -1.1006]])
tensor([[-1.1009,  2.8276,  0.8019],
        [-0.4910, -0.5530,  2.3911]])
tensor([[-0.1602, -1.0389, -0.0616],
        [ 0.5085,  0.6238, -1.4203]])
tensor([[-0.1858, -0.1813, -0.1202],
        [ 0.5088,  1.9869, -1.1725]])


当然，张量和常数间的基本运算也是支持的

In [ ]:
a =torch.randn(2,3)
print(a)
b =torch.mul(a,10)
print(b)
c =torch.div(a,10)
print(c)


tensor([[-1.1340, -0.2232, -0.1493],
        [ 0.6843,  0.9156, -0.0053]])
tensor([[-11.3399,  -2.2316,  -1.4926],
        [  6.8435,   9.1557,  -0.0526]])
tensor([[-0.1134, -0.0223, -0.0149],
        [ 0.0684,  0.0916, -0.0005]])


矩阵乘法计算需要用到`torch.mm`函数

In [ ]:
a = torch.ones(2,3)
b = torch.ones(3,2)
print(a,b,sep='\n')
print(torch.mm(a,b))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[3., 3.],
        [3., 3.]])


### 其他
- `torch.abs`:计算张量的绝对值  
- `torch.pow`:求幂操作

In [ ]:
a = torch.randn(3,3)
print(a,torch.abs(a),sep='\n')

In [ ]:
a = torch.randn(2, 3)
print(a)
b = torch.pow(a, 2)
print(b)


- `Numpy-like`的索引操作

In [ ]:
print(a[:,0])

- `Resize`操作：
如果你想要对tensor进行类似`resize/reshape`的操作，你可以使用  
`torch.view(*shape) -> tensor`: Returns a new tensor with the same data as the self tensor but of a different shape.  
Parameters  
shape (torch.Size or int...) – the desired size

In [ ]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)   # 使用-1时pytorch将会自动根据其他维度进行推导
print(x.size(), y.size(), z.size())  

- `item()`:如果有一个tensor，只包含一个元素，你可以使用.item()来获得它对应的Python形式的取值

In [ ]:
a = torch.randn(1)
print(a,a.size())
print(a.item(),type(a.item()))

- `torch.clamp`：通常我们在需要控制张量的取值范围不越界时，需要用到torch.clamp函数，它可以对输入参数按照自定义的范围进行裁剪，最后将参数裁剪的结果作为输出。输入参数一共有三个，分别是需要进行裁剪的Tensor变量、裁剪的下边界和裁剪的上边界

In [ ]:
import torch
a =torch.randn(2,3)
print(a)
b =torch.clamp(a, -0.5, 0.5)
print(b)

tensor([[ 1.4073, -1.9956,  0.3066],
        [ 1.9485,  1.4006,  0.1117]])
tensor([[ 0.5000, -0.5000,  0.3066],
        [ 0.5000,  0.5000,  0.1117]])


## 3.Numpy桥梁

Pytorch中可以很方便的将Torch的Tensor同Numpy的ndarray进行互相转换，相当于在Numpy和Pytorch间建立了一座沟通的桥梁，这将会让我们的想法实现起来变得非常方便。

注：Torch Tensor 和 Numpy ndarray 底层是分享内存空间的，也就是说改变其中之一会同时改变另一个（前提是你是在CPU上使用Torch Tensor）。**注：所有CPU上的Tensors，除了CharTensor均支持与Numpy的互相转换。**

- 将一个Torch Tensor 转换为 Numpy Array

In [ ]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
# 共享内存空间
a.add_(1)
print(a)
print(b)

- 将一个 Numpy Array 转换为 Torch Tensor

In [79]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b) 

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## 4.CUDA Tensors

通过以下代码进行验证GPU环境：

In [6]:
# 必须切换至GPU环境
print(torch.cuda.is_available())

True


Tensors可以通过.to函数移动到任何我们定义的设备device上，观察如下代码：

In [7]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!  


tensor([[-6.7065e+07,  1.0000e+00,  1.0000e+00],
        [ 1.0000e+00,         nan,  1.0000e+00],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22],
        [ 4.5828e+30,  1.2122e+04,  7.1846e+22],
        [ 1.0000e+00,  7.0374e+22, -1.4291e+07]], device='cuda:0')
tensor([[-6.7065e+07,  1.0000e+00,  1.0000e+00],
        [ 1.0000e+00,         nan,  1.0000e+00],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22],
        [ 4.5828e+30,  1.2122e+04,  7.1846e+22],
        [ 1.0000e+00,  7.0374e+22, -1.4291e+07]], dtype=torch.float64)
